FROM node:20-alpine

# Installation de bash pour les scripts
RUN apk add --no-cache bash

WORKDIR /app

# Copier les fichiers de configuration package
COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

# Installer les dépendances
RUN npm install

# Copier le schéma Prisma et générer le client
COPY prisma ./prisma
RUN npx prisma generate


# Copier tout le code source
COPY src ./src

EXPOSE 3005

# Copier les scripts d'entrypoint et utilitaires dans /app
COPY script ./script
RUN chmod +x ./script/*.sh

# s'assurer que l'image utilise le script d'entrypoint
ENTRYPOINT ["./script/docker-entrypoint.sh"]

# Utilisation du mode développement 
CMD ["npm", "run", "start:dev"]